class SeniorityHealth_urls():

    all_senior_urls = {
        'nav_supp': 'https://shop.seniorityhealth.com/collections/supplements',
        'nav_course': 'https://shop.seniorityhealth.com/collections/workout-courses',
        'nav_stacks': 'https://shop.seniorityhealth.com/collections/workout-courses',
        'nav_apparel': 'https://shop.seniorityhealth.com/collections/apparel',
        'nav_contact': 'https://shop.seniorityhealth.com/pages/contact-us',
        'cart': 'https://shop.seniorityhealth.com/cart',
        'test_reload': 'https://shop.seniorityhealth.com/products/test-reload',
        'leptin_shred': 'https://shop.seniorityhealth.com/products/leptin-shred',
        'afterburn_aminos': 'https://shop.seniorityhealth.com/products/afterburn-aminos',
        'alpha_meal': 'https://shop.seniorityhealth.com/products/alpha-meal',
        'mens_elite': 'https://shop.seniorityhealth.com/products/mens-elite-probiotic',
        'krill': 'https://shop.seniorityhealth.com/products/mens-elite-probiotic',
        'test_max': 'https://shop.seniorityhealth.com/products/testmax-nutrition-new-frb',
        'aa40': 'https://shop.seniorityhealth.com/products/abs-after-40',
        'aa40A': 'https://shop.seniorityhealth.com/products/abs-after-40-advanced',
        'stretch_smart': 'https://shop.seniorityhealth.com/products/smart-stretch',
        'Fit_Fast': 'https://shop.seniorityhealth.com/products/fit-fast',
        'Warr_stack': 'https://shop.seniorityhealth.com/products/marks-warrior-stack',
        'glory': 'https://shop.seniorityhealth.com/products/glory-days-stack',
        'abs_tee': 'https://shop.seniorityhealth.com/products/blue-abs-after-40-t-shirt?variant=23081136449',
        'test_tee': 'https://shop.seniorityhealth.com/products/black-testmax-nutrition-t-shirt?variant=33205064321',
    }