class all_shop_urls():

    shop_urls = {
        'nav_supp': 'https://shop.seniorityhealth.com/collections/supplements',
        'nav_course': 'https://shop.seniorityhealth.com/collections/workout-courses',
        'nav_stacks': 'https://shop.seniorityhealth.com/collections/workout-courses',
        'nav_apparel': 'https://shop.seniorityhealth.com/collections/apparel',
        'nav_contact': 'https://shop.seniorityhealth.com/pages/contact-us',
        'seniority_rx': 'https://shop.seniorityhealth.com/products/exercise-rx',
        'cart': 'https://shop.seniorityhealth.com/cart',
        'test_reload': 'https://shop.seniorityhealth.com/products/test-reload',
        'afterburn_aminos': 'https://shop.seniorityhealth.com/products/afterburn-aminos',
        'alpha_meal': 'https://shop.seniorityhealth.com/products/alpha-meal',
        'mens_elite': 'https://shop.seniorityhealth.com/products/mens-elite-probiotic',
        'krill': 'https://shop.seniorityhealth.com/products/mens-elite-probiotic',
        'test_max': 'https://shop.seniorityhealth.com/products/testmax-nutrition-new-frb',
        'aa40': 'https://shop.seniorityhealth.com/products/abs-after-40',
        'aa40A': 'https://shop.seniorityhealth.com/products/abs-after-40-advanced',
        'stretch_smart': 'https://shop.seniorityhealth.com/products/smart-stretch',
        'Fit_Fast': 'https://shop.seniorityhealth.com/products/fit-fast',
        'glory': 'https://shop.seniorityhealth.com/products/glory-days-stack',
        'abs_tee': 'https://shop.seniorityhealth.com/products/blue-abs-after-40-t-shirt?variant=23081136449',
        'test_tee': 'https://shop.seniorityhealth.com/products/black-testmax-nutrition-t-shirt?variant=33205064321',
        'abs_index': 'https://shop.sixpackabs.com/',
        'supp_page': 'https://shop.sixpackabs.com/collections/supplements',
        'course_page': 'https://shop.sixpackabs.com/collections/collections',
        'stack_page': 'https://shop.sixpackabs.com/collections/stacks',
        'apparel_page': 'https://shop.sixpackabs.com/collections/apparel',
        'contact': 'https://shop.sixpackabs.com/pages/contact-us',
        'cart_abs': 'https://shop.sixpackabs.com/cart',
        'test_reload_abs': 'https://shop.sixpackabs.com/products/test-reload',
        'afterburn_fuel': 'https://shop.sixpackabs.com/products/afterburn-fuel',
        'afterburn_aminos_abs': 'https://shop.sixpackabs.com/products/afterburn-aminos',
        'alpha_armor': 'https://shop.sixpackabs.com/products/alpha-armor',
        'alpha_meal_abs': 'https://shop.sixpackabs.com/products/alpha-meal',
        'probiotic_abs': 'https://shop.sixpackabs.com/products/mens-elite-probiotic',
        'krill_abs': 'https://shop.sixpackabs.com/products/mens-elite-krill-oil',
        'glory_stack': 'https://shop.sixpackabs.com/products/glory-days-stack',
        'abs_tee_abs': 'https://shop.sixpackabs.com/products/blue-abs-after-40-t-shirt?variant=30217035076',
        'sps V_Neck': 'https://shop.sixpackabs.com/products/black-sps-v-neck?variant=30217033348',
        'sps2_hoodie': 'https://shop.sixpackabs.com/products/gray-sps-2-hoodie?variant=30217038148',
        'tmax_shirt': 'https://shop.sixpackabs.com/products/black-testmax-nutrition-t-shirt?variant=39079104964',
        'exercise-rx': 'https://shop.sixpackabs.com/products/exercise-rx',
        'Science_base_six_pack': 'https://deals.sixpackabs.com/science',
        'six pack abs': 'https://sixpackabs.com/',

    }
